<?php 
Class TableCreatorReport{
	public $all = "";

	Public function open($generator="", $tableName="", $classes=array(), $id="table"){
		$this->all .= '<style>
						#table{
						  border-spacing:0;
						  border-collapse:collapse;
						  width:100%;
						}
						#table tr{
						  transition:background-color 0.3s linear 0s;
						}
						#table tr:nth-child(odd){
						  background-color:#D2D2D2;
						}
						#table tr:nth-child(even){
						  background-color:#EBEBEB;
						}
						#table tr td{
						  padding:5px 2px 10px 2px;
						  font-size:12px;
						  
						}
						#table th{
						  color:#000;
						  background:#D3DCE3;
						  padding:5px 2px 10px 2px;
						  font-weight:bold;
						  font-size:13px; 
						  text-align:left;
						  
						  background:#336F89;
						  color:#fff;
						}
						#table tr:hover{
						  background-color:#E3F282;
						  transition:background-color 0.3s linear 0s;
						  color:#000;
						}
						</style>';

		$all_classes = "class = '";
		$all_ids = "";

		foreach ($classes as $value) {
			$all_classes .= "$value ";
		}
		$all_classes .= "' ";

		$all_ids = " id='$id' ";

		$this->all .= '<table id="table" style="font-size:10px;" border="1" cellspacing="0" cellpadding="2"'.$all_classes.$all_ids.'>';

	}

	Public function close(){
		$this->all .= "</tbody></table>";
	}

	Public function th($ths=array()){
		foreach($ths as $th=>$values){			
			$this->all .= "<tr>";
			foreach($ths as $th=>$values){
				$this->all .= "<th>$th</th>";
			}
			$this->all .= "</tr>";
		}
		
	}

	Public function td($tds=array()){
		foreach($tds as $td=>$values){			
			$this->all .= "<tr>";
			foreach($tds as $td=>$values){
				$this->all .= "<td>$td</td>";
			}
			$this->all .= "</tr>";
		}
		
	}

	Public function thd($tds=array()){
		$i=0;
		foreach($tds as $values){
			$total = count($values);

			if($i>=1){

				if ($i%2 == 0) {
                    $this->all .= "<tr style='background-color:#EBEBEB; $align'>";
                } else {
                    $this->all .= "<tr style='background-color:#fff; $align' >";
                }
				

				//$this->all .= "<tr>";
				$this->all .= "<td>".($i).".</td>";

				foreach($values as $val){

					$align = "";
					if(is_int($val)||is_float($val)){
						$align = " text-align:right; ";
					}

					$this->all .= "<td >$val</td>";
					
				}

				$this->all .= "</tr>";
			}else{
				/*
				$this->all .= "<thead><tr><td colspan='$total'>";
				$this->all .= strtoupper($this->tableName);
				$this->all .= '<br/>';
				$this->all .= 'Generated by: '.$this->generator;
				$this->all .= '<br/>';
				$this->all .= 'Date: '.date('Y m d h:i:s A');
				$this->all .= "</td></tr>";	
				*/
				
				$this->all .= "<thead><tr>";
				$this->all .="<th width='30px'>No.</th>";
				foreach($values as $val){
					$this->all .= "<th style='background-color:#336F89; color:#fff;'>$val</th>";
				}
				$this->all .= "</tr></thead><tbody>";
			}
			
			$i++;
		}

		$this->all .= "</tbody>";
		
	}

	Public function results(){
		return $this->all;
	}	

}

?>